name = "CobblemonQuetta"
author = "Hercide"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18680fa2f57c558695546ed7861ad9e463d87a87dd33cdaa8d14dbb45cfb7b25"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "resourcepacks"
