name = "CobblemonQuetta"
author = "Hercide"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e995ab6aa6aeed761a5df9c106ec5514367dfd2ac67964cd11a4390f47922ee"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "resourcepacks"
